### PR TITLE
Changed Calculator.hypotenuse

### LINKED ISSUE #5: Hypotenuse is not computed correctly
The Calculator.hypotenuse method is not computing the correct length for the hypotenuse of the triangle.

### PR DESCRIPTION
**Pull request by ofvoler**
Fixes #5 
Adjusting Calculator.hypotenuse method so the hypotenuse is calculated correctly

### CODE REVIEW

**Comment by siddiquf** [comment]
The pull request shows that conflicts have been created because of the file Calculator.class. Please do not add this class. When you do git add <class name> make sure that you add only Calculator.java.

**Comment by siddiquf** [comment]
The conflict due to Calculator.class still exists

**Comment by ofvoler** [comment]
Do I need to commit again, or is it fixed?

**Comment by siddiquf** [comment]
You will need to issue a new pull request with no conflicts. Is you are having difficulties doing that, please look at the tips posted by Seongho in the class cafe..

**Pull request closed without merging**
